---
version: "3"
services:
  rss2mastodon:
    container_name: rss2mastodon
    image: toozej/rss2mastodon:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.rss2mastodon.rule=Host(`rss2mastodon.test`)"
      # - "traefik.http.routers.rss2mastodon.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.rss2mastodon-secure.entrypoints=https"
      # - "traefik.http.routers.rss2mastodon-secure.rule=Host(`rss2mastodon.test`)"
      # - "traefik.http.routers.rss2mastodon-secure.middlewares=headers@file"
      # - "traefik.http.routers.rss2mastodon-secure.tls=true"
    # networks:
      # - traefik
