# runtime image including CA certs and tzdata
FROM gcr.io/distroless/static-debian12:latest
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/rss2mastodon /go/bin/rss2mastodon
# Expose port for publishing as web service
# EXPOSE 8081
# Run the binary.
ENTRYPOINT ["/go/bin/rss2mastodon"]
